"""The one-pass PMD ruleset: every non-deprecated rule in PMD's eight Java categories, plus the complexity
rules at the PR thresholds and the MethodBody line-range rule.

`generate(jar)` builds the ruleset text from a pmd-java jar's category files; the result is checked in as
`cpr/config/pmd-pr.xml` (regenerate with `python3 -m cpr.staticanalysis.ruleset <pmd-java.jar>` when the PMD
pin changes). `catalog(path)` reads a ruleset back as {rule: category slug}.
"""

import re
import sys
import xml.etree.ElementTree as ET
import zipfile

CATEGORIES = ("bestpractices", "codestyle", "design", "documentation", "errorprone", "multithreading",
              "performance", "security")
# Scored by the Method complexity table, so left out of the PMD rules block.
COMPLEXITY = ("CognitiveComplexity", "CyclomaticComplexity", "NPathComplexity")
# Rules that report nothing useful until configured (LoosePackageCoupling needs package lists).
NEEDS_CONFIG = ("LoosePackageCoupling",)
INTERNAL = ("MethodBody",)

HEAD = """<?xml version="1.0"?>
<ruleset name="pr" xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
  <description>One-pass PR ruleset: cognitive complexity for every method (level 1), cyclomatic and NPath at the skill's thresholds (defaults), method-body line ranges, and every non-deprecated rule of PMD's eight Java categories (generated by cpr.staticanalysis.ruleset).</description>
  <rule ref="category/java/design.xml/CognitiveComplexity"><properties><property name="reportLevel" value="1"/></properties></rule>
  <rule ref="category/java/design.xml/CyclomaticComplexity"/>
  <rule ref="category/java/design.xml/NPathComplexity"/>
  <rule name="MethodBody" language="java" message="body" class="net.sourceforge.pmd.lang.rule.xpath.XPathRule">
    <properties><property name="xpath"><value>//MethodDeclaration/Block | //ConstructorDeclaration/Block | //Initializer/Block</value></property></properties>
  </rule>
"""


def category_rules(xml_text):
    """Names of the live (not deprecated, not a rename reference) rules in one category file."""
    out = []
    for el in ET.fromstring(xml_text):
        if el.tag.rsplit("}", 1)[-1] == "rule" and el.get("name") and el.get("deprecated") != "true" and not el.get("ref"):
            out.append(el.get("name"))
    return out


def wanted(name):
    return name not in COMPLEXITY and name not in NEEDS_CONFIG


def generate(jar):
    """The ruleset text for the category files inside the pmd-java jar at `jar`."""
    lines = []
    with zipfile.ZipFile(jar) as z:
        for cat in CATEGORIES:
            names = [n for n in category_rules(z.read(f"category/java/{cat}.xml")) if wanted(n)]
            lines.append(f"  <!-- {cat}: {len(names)} -->")
            lines += [f'  <rule ref="category/java/{cat}.xml/{n}"/>' for n in sorted(names)]
    return HEAD + "\n".join(lines) + "\n</ruleset>\n"


_REF = re.compile(r"category/java/(\w+)\.xml/(\w+)")


def catalog(ruleset_text):
    """{rule: category slug} for the category rules of a generated ruleset (complexity and internal rules excluded)."""
    out = {}
    for el in ET.fromstring(ruleset_text):
        m = _REF.fullmatch(el.get("ref") or "")
        if m and m[2] not in COMPLEXITY:
            out[m[2]] = m[1]
    return out


if __name__ == "__main__":
    sys.stdout.write(generate(sys.argv[1]))
