"""The PR comment: build it from the report, guard it, and post or edit it with `gh`.

Every `gh` call goes through `run_gh`, the only place that can write to GitHub, so tests replace
that one function. Writes happen only from `post`, and only when the guards pass.
"""

import datetime
import json
import os
import subprocess
import sys
import tempfile

from cpr import REPO, VERSION, net, site
from cpr.ingest import bundle as bundle_mod

PAGES_BASE = "https://pmcfadin.github.io/cassandra-pr-review/pr"
MAX_CHARS = 1500
MAX_REASONS = 5
PUBLISH_FIRST = "publish first: run bin/publish-pages"


class CommentError(Exception):
    """The comment cannot be built or posted; the message says why."""


def run_gh(args, input=None):
    """Run `gh <args>` and return stdout. The single gateway to GitHub; tests replace it."""
    try:
        p = subprocess.run(["gh", *args], input=input, capture_output=True, text=True, timeout=60)
    except (OSError, subprocess.TimeoutExpired) as e:
        raise CommentError(f"gh failed: {e}")
    if p.returncode != 0:
        raise CommentError(f"gh {' '.join(args[:3])} failed: {p.stderr.strip() or p.stdout.strip()}")
    return p.stdout


def fetch_page(url):
    """Body of the published page. Tests replace it. Raises net.NetError (status 404 when missing)."""
    return net.http_get(url)


def pages_url(number):
    return f"{PAGES_BASE}/{number}/"


def marker(number, head=None):
    if head is None:
        return f"<!-- cassandra-pr-review:report pr={number} "
    return f"<!-- cassandra-pr-review:report pr={number} head={head} -->"


def _clip(text, n):
    text = " ".join((text or "").split())
    return text if len(text) <= n else text[:max(n - 1, 0)].rstrip() + "…"


def build_body(model, url=None):
    pr, rec = model["pr"], model["recommendation"]
    number, head = pr["number"], pr["head_sha"]
    url = url or pages_url(number)
    review = model.get("review") or {}
    if review.get("status") == "ran":
        n = review.get("must_fix")
        if n is None:
            c = review.get("issue_counts") or {}
            n = c.get("blocker", 0) + c.get("major", 0)
        summary = f"{n} must-fix issue{'' if n == 1 else 's'} from the code review panel"
    else:
        summary = "no code review run"
    reasons = rec["reasons"][:MAX_REASONS]
    head_lines = [marker(number, head),
                  f"**Automated review report** for `{head[:9]}`: **{rec['label']}** · triage {model['triage']['rating']}",
                  summary + ".", ""]
    tail = ["", f"Full report: {url}", "",
            f"_Advisory only, generated by cassandra-pr-review {VERSION}; committers decide._"]

    def render(limit):
        out = []
        for r in reasons:
            if r.get("lenses"):
                k = len(r["lenses"])
                line = (f"- [{r['severity']}] {r['rule']} — `{r['location']}` "
                        f"({k} lens{'' if k == 1 else 'es'})")
            else:
                line = f"- {r['title']}" + (f": {r['summary']}" if r.get("summary") else "")
            out.append(_clip(line, limit))
        return "\n".join(head_lines + out + tail)

    body = render(300)
    for limit in (200, 140, 100, 60):
        if len(body) <= MAX_CHARS:
            break
        body = render(limit)
    if len(body) > MAX_CHARS:
        raise CommentError("comment too long even with shortened reasons")
    return body


def _json_values(text):
    """All JSON values in `text`; `gh --paginate` prints one array per page back to back."""
    dec, i, out = json.JSONDecoder(), 0, []
    while i < len(text):
        if text[i].isspace():
            i += 1
            continue
        v, i = dec.raw_decode(text, i)
        out.append(v)
    return out


def _flatten(v):
    if isinstance(v, list):
        return [x for item in v for x in _flatten(item)]
    return [v]


def _comments(number):
    text = run_gh(["api", f"repos/{REPO}/issues/{number}/comments", "--paginate", "--slurp"])
    return [c for v in _json_values(text) for c in _flatten(v)]


def find_own(comments, number, login):
    prefix = marker(number)
    for c in comments:
        if (c.get("user") or {}).get("login") == login and prefix in (c.get("body") or ""):
            return c
    return None


def _norm(s):
    return (s or "").replace("\r\n", "\n").strip()


def plan(number, model):
    """Read-only: build the body, look at GitHub and Pages, return what would happen and what blocks it."""
    body = build_body(model)
    head = model["pr"]["head_sha"]
    problems = []
    if not model["recommendation"]["reasons"]:
        problems.append("the recommendation has no reasons to show")
    login = run_gh(["api", "user", "--jq", ".login"]).strip()
    current = json.loads(run_gh(["pr", "view", str(number), "-R", REPO, "--json", "headRefOid"]))["headRefOid"]
    if current != head:
        problems.append(f"local report is for head {head[:9]} but the PR is at {current[:9]}: re-run cpr review")
    live_head, page_error = None, None
    try:
        m = site._MODEL_RE.search(fetch_page(pages_url(number)))
        live_head = json.loads(m.group(1))["pr"]["head_sha"] if m else None
    except net.NetError as e:
        if e.status != 404:
            page_error = str(e)
    if page_error:
        problems.append(f"could not read the published page: {page_error}")
    elif live_head is None:
        problems.append(PUBLISH_FIRST + " (no published report)")
    elif live_head != head:
        problems.append(f"{PUBLISH_FIRST} (Pages shows head {live_head[:9]}, local is {head[:9]})")
    existing = find_own(_comments(number), number, login)
    if existing is None:
        action = "create"
    elif _norm(existing.get("body")) == _norm(body):
        action = "unchanged"
    else:
        action = "edit"
    return {"number": number, "body": body, "head": head, "login": login, "existing": existing,
            "action": action, "problems": problems}


def describe(p):
    verb = {"create": f"create a new comment on {REPO} #{p['number']}",
            "edit": f"edit the existing comment {(p['existing'] or {}).get('html_url')}",
            "unchanged": "do nothing: the existing comment is already up to date"}[p["action"]]
    lines = [p["body"], "", f"--- {len(p['body'])} characters; as {p['login']}", f"Would {verb}."]
    lines += [f"Blocked: {m}" for m in p["problems"]]
    return "\n".join(lines)


def comment_json_path(work_dir, number):
    return os.path.join(bundle_mod.pr_dir(work_dir, number), "comment.json")


def post(p, work_dir, yes=False, is_tty=None, ask=input, now=None):
    """Carry out a plan. Raises CommentError when a guard refuses. Returns the recorded dict."""
    if p["problems"]:
        raise CommentError("refusing to post: " + "; ".join(p["problems"]))
    if p["action"] == "unchanged":
        return {"action": "unchanged", "comment_id": p["existing"]["id"], "url": p["existing"].get("html_url")}
    tty = sys.stdin.isatty() if is_tty is None else is_tty
    if not yes:
        if not tty:
            raise CommentError("no terminal to confirm on: pass --yes to post")
        if ask(f"Post to {REPO} #{p['number']} as {p['login']}? [y/N] ").strip().lower() not in ("y", "yes"):
            raise CommentError("not confirmed; nothing posted")
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as f:
        f.write(p["body"])
        path = f.name
    try:
        if p["action"] == "edit":
            out = run_gh(["api", "-X", "PATCH", f"repos/{REPO}/issues/comments/{p['existing']['id']}",
                          "-F", f"body=@{path}"])
        else:
            out = run_gh(["api", "-X", "POST", f"repos/{REPO}/issues/{p['number']}/comments", "-F", f"body=@{path}"])
    finally:
        os.unlink(path)
    res = json.loads(out)
    when = (now or datetime.datetime.now(datetime.timezone.utc)).strftime("%Y-%m-%dT%H:%M:%SZ")
    rec = {"comment_id": res["id"], "url": res.get("html_url"), "head": p["head"], "posted_at": when}
    target = comment_json_path(work_dir, p["number"])
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w") as f:
        json.dump(rec, f, indent=1)
    return dict(rec, action=p["action"])
