"""Generate an easy-db-lab plan.md for a PR: build the merge-base and the PR head, run the workload that fits
the change, compare. Deterministic (no model call). The plan is text only: nothing here runs easy-db-lab,
provisions anything, or touches the network."""

import json
import os
import re

from cpr import VERSION, paths
from cpr.checks import Context
from cpr.checks.ci import upgrade_sensitive_files
from cpr.checks.compat import touched_surfaces

CONFIG = os.path.join(os.path.dirname(__file__), "config", "labplan.json")
PKG = "src/java/org/apache/cassandra/"
EDB = "$EDB"
SAFE_IDENT = re.compile(r"^[A-Za-z0-9._/-]+$")
SHA40 = re.compile(r"^[0-9a-f]{40}$")
TITLE_KEEP = re.compile(r"[^A-Za-z0-9 \-_.:()]")
JIRA_KEY = re.compile(r"^[A-Z][A-Z0-9]*-\d+$")

BANNER = ("> **Not run.** Generated by cassandra-pr-review {version} from the PR diff on {date}. No cluster was created, "
          "no AWS resource touched, and no command below was executed. Commands are checked against "
          "`easy-db-lab commands` (version {edb}) only for spelling. Review before running.")


def load_config(path=CONFIG):
    with open(path) as f:
        return json.load(f)


def sanitise_title(text, limit=80):
    """Keep alphanumerics, spaces and -_.:() only, collapse whitespace, cut at `limit` characters."""
    s = TITLE_KEEP.sub("", str(text or ""))
    s = re.sub(r"\s+", " ", s).strip()
    return s[:limit].strip()


def _none(reason):
    return {"status": "none", "reason": reason, "scenarios": [], "dropped": [], "markdown": "", "filename": None}


def no_plan_reason(bundle, cfg):
    """Why this PR gets no plan, or None when it should."""
    files = bundle.get("files", [])
    if not files:
        return "the PR changes no files"
    names = [f["path"] for f in files]
    if all(paths.is_doc(p) for p in names):
        return "documentation-only change"
    server = [f for f in files if f["path"].startswith("src/java/") and not paths.is_test(f["path"]) and paths.counted(f)]
    if not server:
        if all(paths.is_test(p) or paths.is_test_resource(p) for p in names):
            return "tests-only change"
        if all(re.match(r"^(lib/|\.build/(build-resolve|parent-pom-template|cassandra-deps-template|cassandra-build-deps-template)\.xml)", p)
               for p in names):
            return "dependency change"
        if all(paths.is_build(p) for p in names):
            return "build or CI change"
        if all(paths.is_generated(p) for p in names):
            return "generated files only"
        return "no server code under src/java changed (tooling, configuration or Python only)"
    if len(server) > cfg["max_prod_files"]:
        return (f"{len(server)} production files changed (limit {cfg['max_prod_files']}): an A-B run would not isolate "
                "any one change; split the PR")
    return None


def _matches(rule, path, sensitive, surface_paths, text):
    rel = path[len(PKG):] if path.startswith(PKG) else None
    hit = bool(rel is not None and any(rel.startswith(p) for p in rule.get("prefixes", [])))
    hit = hit or any(re.search(rx, path) for rx in rule.get("regex", []))
    hit = hit or (rule.get("upgrade_sensitive") and path in sensitive)
    hit = hit or any(path in surface_paths.get(s, ()) for s in rule.get("surfaces", []))
    if not hit:
        return False
    if rule.get("keywords") and not re.search(rule["keywords"], text, re.I):
        return False
    if rule.get("exclude_keywords") and re.search(rule["exclude_keywords"], text, re.I):
        return False
    return True


def select(bundle, cfg):
    """Rank scenarios from the rules. Returns (chosen, dropped); each is {id, rules, priority, lines, files, paths}."""
    ctx = Context(bundle)
    sensitive = set(upgrade_sensitive_files(ctx))
    surface_paths = touched_surfaces([f["path"] for f in bundle["files"]])
    ticket = (bundle.get("jira") or {}).get("ticket") or {}
    text = f"{bundle['pr'].get('title', '')} {ticket.get('summary', '')}"
    prod = [f for f in bundle["files"] if f["path"].startswith("src/java/") and not paths.is_test(f["path"])
            and paths.counted(f)]
    by_scn = {}
    for rule in cfg["rules"]:
        covered = [f for f in prod if _matches(rule, f["path"], sensitive, surface_paths, text)]
        lines = sum(f["additions"] + f["deletions"] for f in covered)
        if not covered or lines < rule["min_lines"]:
            continue
        s = by_scn.setdefault(rule["scenario"], {"id": rule["scenario"], "rules": [], "priority": 0, "files": {}})
        s["rules"].append(rule["id"])
        s["priority"] = max(s["priority"], rule["priority"])
        for f in covered:
            s["files"][f["path"]] = f["additions"] + f["deletions"]
    ranked = []
    for s in by_scn.values():
        ranked.append({"id": s["id"], "rules": s["rules"], "priority": s["priority"], "lines": sum(s["files"].values()),
                       "files": len(s["files"]),
                       "paths": [p for p, _ in sorted(s["files"].items(), key=lambda kv: (-kv[1], kv[0]))]})
    ranked.sort(key=lambda s: (-s["priority"], -s["lines"], s["id"]))
    if not ranked:
        top = sorted(prod, key=lambda f: (-(f["additions"] + f["deletions"]), f["path"]))
        ranked = [{"id": "smoke", "rules": ["default-smoke"], "priority": 0, "lines": sum(f["additions"] + f["deletions"] for f in prod),
                   "files": len(prod), "paths": [f["path"] for f in top]}]
    return ranked[:cfg["max_scenarios"]], ranked[cfg["max_scenarios"]:]


# ---------------------------------------------------------------------------
# Step text. Every bash block is plain commands; nothing from the PR except validated identifiers.
# ---------------------------------------------------------------------------

class Ctx:
    def __init__(self, cfg, n, base_sha, head_sha, head_repo, base_branch):
        self.cfg, self.n = cfg, n
        self.base_sha, self.head_sha, self.head_repo, self.base_branch = base_sha, head_sha, head_repo, base_branch
        self.cluster = f"pr{n}-{head_sha[:7]}"
        self.java = cfg["java_by_branch"].get(base_branch, cfg["java_default"])
        self.data = cfg["cluster"]["data_dir"]
        self.hosts = [f"db{i}" for i in range(cfg["cluster"]["db_count"])]
        self.base, self.head = f"pr{n}-base", f"pr{n}-head"


def bash(*lines):
    return "```bash\n" + "\n".join(lines) + "\n```"


def reset_lines(c, arm_ref, indent=""):
    d = c.data
    return [f'{indent}{EDB} cassandra stop',
            f'{indent}{EDB} exec run -t cassandra bash -c "find {d} -mindepth 1 -delete; exit 0"',
            f'{indent}{EDB} exec run -t cassandra bash -c "find {d} -mindepth 1 | wc -l; exit 0"   # expect 0 on every node',
            f'{indent}{EDB} cassandra use {arm_ref}',
            f'{indent}{EDB} cassandra start',
            f'{indent}{EDB} cassandra nt status']


def common_steps(c):
    cfg, n = c.cfg, c.n
    cl = cfg["cluster"]
    wf, br = cfg["builds_workflow"], cfg["builds_repo"]
    steps = []
    steps.append(("Build both refs (owner's machine)",
                  "Builds run in a cassandra-builds repo whose workflows you can dispatch. The repo below is the default; "
                  "change `BUILDS` to your fork if you cannot dispatch there. Both refs are full SHAs, never branch names.\n"
                  + bash(f"BUILDS={br}",
                         f"gh workflow run {wf} -R $BUILDS -f repo={cfg['base_repo']} -f ref={c.base_sha}",
                         f"gh workflow run {wf} -R $BUILDS -f repo={c.head_repo} -f ref={c.head_sha}",
                         f"gh run list -R $BUILDS -w {wf} -L 2") + "\n"
                  f"**Pass:** both runs show `success`, and `gh release view <sha> -R $BUILDS` lists a `-bin.tar.gz` for each SHA.\n"
                  "**Fail:** either run fails; stop here."))
    steps.append(("Provision",
                  bash(f"{EDB} init {c.cluster} --db.count {cl['db_count']} --app.count {cl['app_count']} "
                       f"--db.instance-type {cl['instance_type']} --app.instance-type {cl['instance_type']} --up",
                       f"{EDB} status") + "\n**Pass:** all nodes are up."))
    sel = '.assets[] | select(.name | endswith("-bin.tar.gz")) | .url'
    steps.append(("Install both builds on all nodes",
                  bash(f"URL_BASE=$(gh release view {c.base_sha} -R $BUILDS --json assets --jq '{sel}')",
                       f"URL_HEAD=$(gh release view {c.head_sha} -R $BUILDS --json assets --jq '{sel}')",
                       f'{EDB} cassandra install {c.base} --java {c.java} --url "$URL_BASE"',
                       f'{EDB} cassandra install {c.head} --java {c.java} --url "$URL_HEAD"') + "\n"
                  f"**Pass:** both directories exist on {', '.join(c.hosts)} "
                  '(`ssh -F "$(dirname "$EDB")/sshConfig" db0 ls /usr/local/cassandra`).'))
    return steps


def calibrate_step(c):
    cal = c.cfg["calibration"]
    n = c.n
    return ("Calibrate (base, %d x %d min)" % (cal["runs"], cal["minutes"]),
            "Two identical runs on the base build give the error bar for every delta below.\n"
            + bash(*reset_lines(c, c.base),
                   f"for k in {' '.join(str(i + 1) for i in range(cal['runs']))}; do",
                   f'  {EDB} cassandra stress start --name cal-$k --tags "arm=base,phase=cal,pr={n}" -- {cal["workload"]} -d {cal["minutes"]}m',
                   f"  sleep {cal['minutes'] * 60 + 60}   # stress start returns before the job ends (unverified)",
                   f"  {EDB} cassandra stress logs cal-$k --tail 40",
                   "done") + "\n"
            "**Record:** ops/s and p99 of both runs. Spread = the difference between them; it is the error bar.")


def _measure_block(c, sc, workloads_fn, indent="  "):
    d = c.data
    lines = []
    for label, args in workloads_fn:
        name = f"{label}-$arm-$k"
        lines += [f'{indent}{EDB} cassandra stress start --name {name} --tags "arm=$arm,run=$k,pr={c.n}" -- {args}',
                  f"{indent}sleep {sc['measured_minutes'] * 60 + 60}   # job length plus a minute; stress start returns early (unverified)",
                  f"{indent}{EDB} cassandra stress logs {name} --tail 40"]
    lines += [f"{indent}{EDB} cassandra nt gcstats",
              f"{indent}{EDB} cassandra nt tpstats",
              f"{indent}{EDB} cassandra nt compactionstats",
              f'{indent}{EDB} exec run -t cassandra bash -c "grep -c ERROR {d}/logs/system.log; exit 0"',
              f"{indent}{EDB} cassandra stress stop --all --force"]
    return lines


def perf_setup(c, sc):
    """Steps that must precede calibration (the calibration arm needs the same config)."""
    if not sc.get("needs_accord"):
        return []
    return [("Enable Accord in the patch file (complete file, never a stub)",
             bash(f"{EDB} cassandra use {c.base}",
                  f"{EDB} cassandra write-config cassandra.patch.yaml",
                  "# append to cassandra.patch.yaml (keep every existing key):",
                  "#   accord:",
                  "#     enabled: true",
                  f"{EDB} cassandra update-config cassandra.patch.yaml") + "\n"
             "`use` re-applies `cassandra.patch.yaml`, so the setting survives every arm switch.\n"
             "**Pass:** the file on each node shows `enabled: true` and its original seeds and cluster name.\n"
             "**Unverified until run:** that `accord.enabled` is the only switch this build needs, and that the "
             "workload sets `transactional_mode='full'` itself.")]


def perf_steps(c, sc):
    cfg = c.cfg
    steps = []
    arms = " ".join(cfg["arm_order"])
    workloads = [(w["label"], f"{w['args']} -d {sc['measured_minutes']}m") for w in sc["workloads"]]
    body = ['k=0', f"for arm in {arms}; do", "  k=$((k+1))"]
    body += reset_lines(c, f"pr{c.n}-$arm", "  ")
    body += _measure_block(c, sc, workloads)
    body += ["done"]
    steps.append((f"Measured runs, order A B B A ({sc['title']})",
                  "Data is wiped between arms. Each job is tagged with its arm and run number.\n"
                  + bash(*body) + "\n"
                  "**Pass:** for every workload, head ops/s and p99 are within 2x the calibration spread of base in both "
                  "A-B pairs, and head logs no new `ERROR` lines.\n"
                  "**Fail:** head is outside that spread in both pairs, or logs new errors or timeouts.\n"
                  "**No detectable difference:** a delta below 2x the calibration spread, or in only one pair.\n"
                  "**Unverified until run:** the data directory path and whether `stress start` returns before the job ends."))
    return steps


def crash_loop(c, arm_ref, arm, cycles):
    cfg, d = c.cfg, c.data
    pat = cfg["crash"]["log_pattern"]
    wl = cfg["scenarios"]["crash"]["workload"]
    return [f'{EDB} cassandra cql "CREATE KEYSPACE IF NOT EXISTS crash WITH replication={{\'class\':\'SimpleStrategy\',\'replication_factor\':3}}"',
                f'{EDB} cassandra stress start --name {arm}-load --tags "arm={arm},pr={c.n}" -- {wl}',
                f"for i in $(seq 1 {cycles}); do",
                f"  {EDB} cassandra nt --hosts db1 flush",
                f"  {EDB} cassandra nt --hosts db1 compact",
                "  sleep $((RANDOM % 8))",
                f'  {EDB} exec run -t cassandra --hosts db1 bash -c "sudo systemctl kill -s KILL cassandra; exit 0"',
                f"  {EDB} cassandra start --hosts db1",
                f"  {EDB} exec run -t cassandra --hosts db1 bash -c \"grep -E -c '{pat}' {d}/logs/system.log; exit 0\"",
                "done"]


def crash_steps(c, sc):
    cfg = c.cfg
    cyc, ext = cfg["crash"]["cycles"], cfg["crash"]["extended_cycles"]
    steps = [(f"Arm A (base): start and crash {cyc} times",
              "Tiny sstables and aggressive compaction maximise obsolete-sstable deletions per minute; each cycle flushes, "
              "compacts, then kills the process on one node and restarts it.\n"
              + bash(*reset_lines(c, c.base), *crash_loop(c, c.base, "base", cyc)) + "\n"
              "**Record:** cycles where db1 did not return to UN, and the count of matching log lines per cycle.\n"
              "**Unverified until run:** the systemd unit name `cassandra`, whether `start --hosts` waits for UN, and the log path."),
             (f"Arm B (head): reset, switch builds, crash {cyc} times",
              bash(*reset_lines(c, c.head), *crash_loop(c, c.head, "head", cyc)) + "\n"
              f"**Pass:** head restarts in {cyc}/{cyc} cycles with 0 matching log lines, and base showed at least one failure.\n"
              "**Fail:** any failed restart or matching log line on head.\n"
              f"**Inconclusive:** base shows 0 failures in {cyc} cycles (the control cannot fail); extend to {ext} cycles or "
              "mark the result not informative. Do not report this as fixed.")]
    return steps


def node_ops_steps(c, sc):
    d = c.data
    arms = " ".join(c.cfg["arm_order"])
    body = ["k=0", f"for arm in {arms}; do", "  k=$((k+1))"]
    body += reset_lines(c, f"pr{c.n}-$arm", "  ")
    body += [f'  {EDB} cassandra stress start --name bg-$arm-$k --tags "arm=$arm,run=$k,pr={c.n}" -- {sc["workload"]} -d {sc["measured_minutes"] + 15}m',
             "  sleep 300   # warm up",
             f"  {EDB} cassandra stop --hosts db2",
             "  sleep 600   # node down for 10 minutes",
             f"  {EDB} cassandra start --hosts db2",
             f"  time {EDB} cassandra nt --hosts db2 repair -full",
             f"  {EDB} cassandra nt netstats",
             f"  {EDB} cassandra stress logs bg-$arm-$k --tail 40",
             f'  {EDB} exec run -t cassandra bash -c "grep -c ERROR {d}/logs/system.log; exit 0"',
             f"  {EDB} cassandra stress stop --all --force",
             "done"]
    return [(f"Repair after downtime, order A B B A ({sc['title']})",
             "Background load runs while one node is down for 10 minutes, then restarts and is repaired.\n"
             + bash(*body) + "\n"
             "**Record:** repair wall time, streamed bytes, and p99 of the background job during repair.\n"
             "**Pass:** head repair time and streamed bytes are within 2x the calibration spread of base in both A-B pairs, with no new errors.\n"
             "**Fail:** head repair is slower or errors in both pairs.\n"
             "**Unverified until run:** whether `nt` needs `--` before arguments that start with a dash.")]


def mixed_version_steps(c, sc):
    d = c.data
    first, rest = c.hosts[-1], c.hosts[:-1]
    wl = f"{sc['workload']} -d {sc['measured_minutes']}m"
    up = [f"{EDB} cassandra stop --hosts {first}", f"{EDB} cassandra use --hosts {first} {c.head}",
          f"{EDB} cassandra start --hosts {first}", f"{EDB} cassandra nt status"]
    steps = [("Start the ring on the base build",
              bash(*reset_lines(c, c.base),
                   f'{EDB} cassandra stress start --name seed --tags "arm=base,phase=seed,pr={c.n}" -- KeyValue -r 0 -t 16 -p 1m -d 3m',
                   "sleep 240   # stress start returns before the job ends (unverified)") + "\n**Pass:** all nodes UN."),
             (f"Upgrade one node ({first}) to the PR build and run mixed",
              bash(*up,
                   f'{EDB} cassandra stress start --name mixed --tags "arm=mixed,pr={c.n}" -- {wl}',
                   f"sleep {sc['measured_minutes'] * 60 + 60}",
                   f"{EDB} cassandra stress logs mixed --tail 40",
                   f'{EDB} exec run -t cassandra bash -c "grep -c ERROR {d}/logs/system.log; exit 0"') + "\n"
              "**Pass:** the job shows no errors, all nodes UN, and schema agreement (`nt describecluster`).\n"
              "**Fail:** client errors, a node that does not rejoin, or schema disagreement."),
             ("Upgrade the remaining nodes",
              bash(*[l for h in rest for l in (f"{EDB} cassandra stop --hosts {h}", f"{EDB} cassandra use --hosts {h} {c.head}",
                                               f"{EDB} cassandra start --hosts {h}")],
                   f"{EDB} cassandra nt status",
                   f"{EDB} cassandra nt describecluster",
                   f"{EDB} cassandra nt upgradesstables") + "\n"
              "**Pass:** all nodes UN on the PR build and the ring still serves reads written before the upgrade. "
              "Skip `upgradesstables` when the change does not alter the sstable format.")]
    return steps


def smoke_steps(c, sc):
    d = c.data
    return [("Start the PR build and exercise it",
             bash(*reset_lines(c, c.head),
                  f'{EDB} cassandra cql "SELECT release_version FROM system.local"',
                  f'{EDB} cassandra stress start --name smoke --tags "arm=head,pr={c.n}" -- {sc["workload"]} -d {sc["measured_minutes"]}m',
                  f"sleep {sc['measured_minutes'] * 60 + 60}   # stress start returns before the job ends (unverified)",
                  f"{EDB} cassandra stress logs smoke --tail 40",
                  f'{EDB} exec run -t cassandra bash -c "grep -c ERROR {d}/logs/system.log; exit 0"') + "\n"
             "Then run the changed command, query, vtable or metric by hand (see Notes for the changed paths) and record the output.\n"
             "**Pass:** all nodes UN, the job completes with no errors, and the changed feature behaves as the ticket describes.\n"
             "**Fail:** a node does not start, errors appear in the job or `system.log`, or the feature fails.")]


KINDS = {"perf": perf_steps, "crash": crash_steps, "node-ops": node_ops_steps, "mixed-version": mixed_version_steps,
         "smoke": smoke_steps}


def results_table(c, kinds):
    if "crash" in kinds and len(kinds) == 1:
        return ("| arm | cycles | failed restarts | matching log lines |\n|---|---|---|---|\n"
                "| base |  |  |  |\n| head |  |  |  |")
    rows = "\n".join(f"| {arm} | {i + 1} |  |  |  |  |  |" for i, arm in enumerate(c.cfg["arm_order"]))
    return "| arm | run | ops/s | p99 ms | GC ms/s | pending compactions | errors |\n|---|---|---|---|---|---|---|\n" + rows


def objective(c, chosen_cfg, chosen):
    parts = []
    for sel, sc in zip(chosen, chosen_cfg):
        if sc["kind"] == "crash":
            parts.append("Hypothesis: on the base build, `kill -9` during compaction can leave state that fails recovery at "
                         "restart (a node that will not start, or error lines in `system.log`); on the PR build it never does. "
                         "Success: head restarts cleanly in every cycle and base reproduces the failure at least once.")
        elif sc["kind"] in ("perf", "node-ops"):
            parts.append(f"Hypothesis: {sc['hypothesis']}. Success: head p99 <= base p99 + 2x the calibration spread and ops/s >= "
                         "base - 2x the spread, in both A-B pairs; otherwise report no detectable difference.")
        else:
            parts.append(f"Hypothesis: {sc['hypothesis']}. Success: all nodes UN and no errors.")
    if len(parts) > 1:
        parts = [f"**{i}. {sc['title'].capitalize()}.** {p}" for i, (sc, p) in enumerate(zip(chosen_cfg, parts), 1)]
    return "\n\n".join(parts)


def build_plan(bundle, cfg=None):
    """Return the lab plan for a PR: {status: "plan"|"none", reason, scenarios, dropped, markdown, filename, ...}."""
    cfg = cfg or load_config()
    reason = no_plan_reason(bundle, cfg)
    if reason:
        return _none(reason)
    pr = bundle["pr"]
    base_sha, head_sha, head_repo = bundle["git"]["merge_base"], pr["head_sha"], pr.get("head_repo")
    if not (SHA40.match(str(base_sha)) and SHA40.match(str(head_sha))):
        return _none("the merge-base or head commit is not a full 40-character SHA")
    if not head_repo or not SAFE_IDENT.match(head_repo):
        return _none("the head repository is missing or has an unusual name (the PR fork may have been deleted)")
    if not SAFE_IDENT.match(str(pr.get("base", ""))):
        return _none("the base branch has an unusual name")
    chosen, dropped = select(bundle, cfg)
    n = pr["number"]
    c = Ctx(cfg, n, base_sha, head_sha, head_repo, pr["base"])
    scs = [cfg["scenarios"][s["id"]] for s in chosen]

    steps = common_steps(c)
    for sc in scs:
        if sc["kind"] == "perf":
            steps += perf_setup(c, sc)
    if any(sc["kind"] == "perf" for sc in scs):
        steps.append(calibrate_step(c))
    for sc in scs:
        steps += KINDS[sc["kind"]](c, sc)
    steps.append(("Collect results",
                  "Fill the results table below from the job logs and `nt` output, apply the decision rule from the Objective, "
                  "and write the verdict (fixed, no detectable difference, regression, or inconclusive) next to it.\n"
                  + bash(f"{EDB} cassandra nt status", f"{EDB} cassandra stress status")))
    steps.append(("Teardown",
                  bash(f"{EDB} down --auto-approve",
                       f"gh release delete {base_sha} -R $BUILDS --cleanup-tag --yes",
                       f"gh release delete {head_sha} -R $BUILDS --cleanup-tag --yes") + "\n"
                  "Per-SHA releases accumulate; skip the last two lines if another plan uses the same SHA."))

    ticket = (bundle.get("jira") or {}).get("ticket") or {}
    key = (bundle.get("jira_key") or {}).get("key")
    key = key if key and JIRA_KEY.match(key) else None
    title = sanitise_title(pr.get("title", ""), cfg["title_max"])
    heading = f"# Lab Plan: PR {n}" + (f" {key}" if key and key not in title else "") + (f" {title}" if title else "") + f" ({pr['base']})"
    date = str(bundle.get("meta", {}).get("fetched_at", ""))[:10] or "an unknown date"
    hours = sum(sc["hours"] for sc in scs)
    cl = cfg["cluster"]

    lead = chosen[0]
    changed = [p for p in lead["paths"] if SAFE_IDENT.match(p)][:5]
    notes = []
    for sel, sc in zip(chosen, scs):
        notes.append(f"Scenario **{sc['title']}** was chosen by rule `{'`, `'.join(sel['rules'])}` "
                     f"({plural(sel['files'], 'production file')}, {sel['lines']} changed lines).")
    if changed:
        notes.append("Changed paths behind the first scenario: " + ", ".join(f"`{p}`" for p in changed)
                     + (f" and {lead['files'] - len(changed)} more" if lead["files"] > len(changed) else "") + ".")
    if dropped:
        notes.append("Not run because of the cap of %d scenarios: %s." % (
            cfg["max_scenarios"], "; ".join(f"{cfg['scenarios'][d['id']]['title']} (rule `{'`, `'.join(d['rules'])}`, "
                                            f"{plural(d['files'], 'file')})" for d in dropped)))
    if any(sc.get("needs_accord") for sc in scs) and pr["base"] != "trunk":
        notes.append(f"The Accord scenario assumes a build that includes Accord; confirm `{pr['base']}` does before running.")
    if any(sel["id"] == "crash" for sel in chosen):
        notes.append("The failure window can be small: an inconclusive base arm is an expected outcome, not a plan defect.")
    notes.append(f"Estimated wall clock {hours:g} h on {cl['db_count']} + {cl['app_count']} {cl['instance_type']} instances; "
                 "confirm on the first real run. Perf deltas count only above 2x the calibration spread and when they appear in both A-B pairs.")
    notes.append("Every command was checked for spelling only. Items marked 'Unverified until run' are taken from the easy-db-lab "
                 "plugin documentation and have not been executed by this tool.")

    md = [heading, "",
          BANNER.format(version=VERSION, date=date, edb=cfg["edb_version"]), "",
          "## Objective", objective(c, scs, chosen), "",
          "## Cluster Name", c.cluster, "",
          "## Datacenters", "single", "",
          "## Environment",
          f"{cl['db_count']} db + {cl['app_count']} app, {cl['instance_type']}, {pr['base']} (JDK {c.java}). "
          f"Base = {base_sha[:12]} ({cfg['base_repo']}); head = {head_sha[:12]} ({head_repo}).", "",
          "## Artifacts under test",
          "| | base | head |", "|---|---|---|",
          f"| repo / ref | {cfg['base_repo']} @ {base_sha} | {head_repo} @ {head_sha} |",
          f"| build | `{cfg['builds_workflow']}` | `{cfg['builds_workflow']}` |",
          f"| installed as | `{c.base}` | `{c.head}` |", "",
          "## Steps", ""]
    for i, (name, body) in enumerate(steps, 1):
        md += [f"### {i}. {name}", body, ""]
    md += ["## Results table (fill in)", results_table(c, {sc["kind"] for sc in scs}), "",
           "## Notes"] + notes
    text = "\n".join(md) + "\n"
    return {"status": "plan", "reason": None, "markdown": text, "filename": f"plan-{n}.md", "cluster": c.cluster,
            "generated": date, "hours": hours,
            "scenarios": [{"id": s["id"], "title": cfg["scenarios"][s["id"]]["title"], "rules": s["rules"],
                           "files": s["files"], "lines": s["lines"]} for s in chosen],
            "dropped": [{"id": d["id"], "title": cfg["scenarios"][d["id"]]["title"], "rules": d["rules"],
                         "files": d["files"]} for d in dropped]}


def plural(n, word):
    return f"{n} {word}{'' if n == 1 else 's'}"


def section_summary(plan):
    if plan["status"] != "plan":
        return f"No lab plan: {plan['reason']}"
    return "Plan for " + " and ".join(s["title"] for s in plan["scenarios"]) + " (not run)"
